on:
  push:
    branches:
      - master
  workflow_dispatch:
  
env:
  AZURE_WEBAPP_NAME: carlen
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Building web app
      uses: azure/appservice-build@v2
    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: production
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1be93452d5f047fabcef09eb7220f207 }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
